import Entrance from '../assets/Entrance.png'
import Descend from '../assets/Descend.png'
import Shop from '../assets/Shop.png'
import Wall from '../assets/Wall.png'
import Rat from '../assets/Rat.png'
import Spider from '../assets/Spider.png'
import Snake from '../assets/Snake.png'
import Dragon from '../assets/Dragon.png'
import Sword from '../assets/Sword.png'
import Staff from '../assets/Staff.png'
import Bow from '../assets/Bow.png'
import Armor from '../assets/Armor.png'
import Gauntlets from '../assets/Gauntlets.png'
import Helm from '../assets/Helm.png'
import Coin from '../assets/Coin.png'
import Open from '../assets/Open.png'
import InvSword from '../assets/InvSword.png'
import InvStaff from '../assets/InvStaff.png'
import InvBow from '../assets/InvBow.png'
import InvArmor from '../assets/InvArmor.png'
import InvGauntlets from '../assets/InvGauntlets.png'
import InvHelm from '../assets/InvHelm.png'
import InvCoin from '../assets/InvCoin.png'
import InvKey from '../assets/InvKey.png'
import InvNoSword from '../assets/InvNoSword.png'
import InvNoStaff from '../assets/InvNoStaff.png'
import InvNoBow from '../assets/InvNoBow.png'
import InvNoArmor from '../assets/InvNoArmor.png'
import InvNoGauntlets from '../assets/InvNoGauntlets.png'
import InvNoHelm from '../assets/InvNoHelm.png'
import InvNoCoin from '../assets/InvNoCoin.png'
import InvNoKey from '../assets/InvNoKey.png'

export default {
  Entrance, Descend, Shop, Wall, Rat, Spider, Snake, Dragon, Sword, Staff, Bow, Armor, Gauntlets, Helm, Coin, Open, InvSword, InvStaff, InvBow, InvArmor, InvGauntlets, InvHelm, InvCoin, InvKey, InvNoSword, InvNoStaff, InvNoBow, InvNoGauntlets, InvNoHelm, InvNoCoin, InvNoKey, InvNoArmor
}
